language: node_js

node_js:
  - "10"
  - "11"

install:
  - npm i codecov -g
  - npm i
  - npm run build

script:
  - npm run test

after_success:
  # - npm run coverage
  - codecov -f ./packages/workit-camunda/coverage/*.json
  - git remote set-url origin git@${GH_TOKEN}@github.com:${TRAVIS_REPO_SLUG}.git

git:
  depth: 5

cache:
  directories:
    - node_modules

# before_deploy:
#   - cp .npmrc.template ~/.npmrc

# deploy: #npx lerna version patch and push to git
#   provider: script
#   email: olivier.albertini@montreal.ca
#   api_key: $NPM_AUTH_TOKEN
#   skip_cleanup: true
#   script: npx lerna publish -y from-git
#   on:
#     node: "10"
#     tags: true
#     branch: master