apiVersion: v1
kind: ConfigMap
metadata:
  name: zeebe-config
  labels:
    app: zeebe-config
data:
  zeebe.cfg.toml: |
    [[exporters]]
        id = "simple-monitor"
        className = "io.zeebe.monitor.SimpleMonitorExporter"

        [exporters.args]
          jdbcUrl = "jdbc:h2:tcp://zeebe-db:1521/zeebe-monitor"
          driverName = "org.h2.Driver"
          userName = "sa"
          password = ""