apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeebe-monitor
  labels:
    app: zeebe-monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zeebe-monitor
    spec:
      containers:
      - name: zeebe-simple-monitor
        image: camunda/zeebe-simple-monitor:latest
        ports:
        - name: http-port
          containerPort: 8080
        env:
          - name: spring.datasource.url
            value: jdbc:h2:tcp://zeebe-db:1521/zeebe-monitor
          - name: io.zeebe.monitor.connectionString
            value: zeebe:26500
