apiVersion: v1
kind: Service
metadata:
  name: zeebe-monitor
  labels:
    app: zeebe-monitor
spec:
  ports:
  - port: 8080
    nodePort: 32066
    targetPort: http-port
    protocol: TCP
  type: NodePort
  selector:
    app: zeebe-monitor